version: '3.1'

services:
  db:
    container_name: mysqlcda
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - 3308:3306
  adminer:
    container_name: adminercda
    image: adminer:4-standalone
    restart: always
    ports:
    - 9080:8080
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9180:80
    environment:
      - PMA_ARBITRARY=1
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
    - 9081:80
      # Change the number before : to the port the SMTP server should be accessible on
    - 9025:25
     